import { Project } from '@/types'

export const projects: Project[] = [
  {
    id: 'project-1',
    slug: 'immersive-commerce',
    title: 'Immersive Commerce',
    description:
      'A WebGL-powered e-commerce experience featuring real-time 3D product configuration and seamless page transitions.',
    tech: ['Next.js', 'Three.js', 'R3F', 'GSAP'],
    year: '2024',
    client: 'Luxury Retailer',
    role: 'Lead Creative Developer',
    link: 'https://example.com',
    github: 'https://github.com',
    image: '/images/project-1.jpg',
    challenge: 'The client needed to bridge the gap between physical luxury shopping and the digital experience. The goal was to create a product configurator that felt tactile and responsive, without compromising on performance or SEO.',
    solution: 'We built a custom WebGL renderer using React Three Fiber, optimized for mobile devices. The 3D assets were compressed using Draco, and we implemented a custom shader pipeline for realistic material representation. The result was a 40% increase in engagement and a 15% conversion uplift.',
    gallery: ['/images/project-1.jpg', '/images/project-2.jpg', '/images/project-3.jpg'],
  },
  {
    id: 'project-2',
    slug: 'financial-dashboard',
    title: 'Financial Dashboard',
    description:
      'High-performance real-time data visualization platform handling millions of data points with sub-millisecond updates.',
    tech: ['React', 'D3.js', 'WebSocket', 'TypeScript'],
    year: '2023',
    client: 'FinTech Corp',
    role: 'Senior Frontend Engineer',
    link: 'https://example.com',
    github: 'https://github.com',
    image: '/images/project-2.jpg',
    challenge: 'Traders needed to visualize complex market data in real-time with zero latency. Existing solutions were sluggish and difficult to customize.',
    solution: 'I architected a WebSocket-based data layer that fed into a custom D3.js rendering engine. By using Canvas API for high-frequency updates and React for UI controls, we achieved 60fps rendering even during peak market volatility.',
    gallery: ['/images/project-2.jpg', '/images/project-3.jpg', '/images/project-1.jpg'],
  },
  {
    id: 'project-3',
    slug: 'ai-generative-studio',
    title: 'AI Generative Studio',
    description:
      'Browser-based interface for generative art creation, leveraging WebGPU for client-side inference.',
    tech: ['WebGPU', 'React', 'Node.js', 'TensorFlow.js'],
    year: '2023',
    client: 'ArtTech Startup',
    role: 'Creative Technologist',
    link: 'https://example.com',
    github: 'https://github.com',
    image: '/images/project-3.jpg',
    challenge: 'Running generative AI models typically requires expensive server GPUs. The goal was to bring this capability to the browser to reduce costs and improve privacy.',
    solution: 'Leveraging the new WebGPU API, we ported stable diffusion models to run entirely client-side. This required extensive optimization of the compute shaders and memory management, resulting in a near-native performance experience in Chrome.',
    gallery: ['/images/project-3.jpg', '/images/project-1.jpg', '/images/project-2.jpg'],
  },
]
